### ISSUE TITLE
Scalability + Obstacle avoidance ?

### ISSUE THREAD

**Issue by collant** [pauzii/PhaseBetweener#2]
I have been playing with it, performance wise it is very interesting (unlike what someone commented in Youtube).

I have two questions if you can answer them:

1- At what extent do you thing this is scalable to add more motion to fill the gaps? we might need to add more parameters to the model, but what do you think about performance?

2- Is there anyway I can hack it to add obstacle avoidance, like there is a wall between the control and target, and it has to pass by the door, or do you think this is has to be managed by a high level policy, it can be handled for navigation, but sometimes you have 3d obstacles that needs particular motion. Can these obstacle meshes be baked into the latent space somehow?

**Comment by paulstarke** [comment]
Hi @collant!

1) Motion variety depends on your training data. If you only have locomotion data then it won't be possible to generalize to a spin kick or something. Adding diverse training data will scale the in-between motions. 
I wouldn't worry too much about performance, even when you animate multiple characters you can batch inputs.

2) With the current system, one intuitive way to achieve obstacle avoidance is on the control-level. You can use the trajectory input for the system (similar as what we showed with the Authoring tool) to guide the character motion along a path. If you generate a collision-free path between the objects you can instruct the system to follow this path and generate the corresponding motion while doing so. 

Learning collision-avoidance and motion progression is not trivial and would require the geometry data (meshes) during training. Even when having such data I'm not sure how much the motion quality will suffer under those conditions as learning this is high ambiguous.
