### ISSUE TITLE
Wrong expected training data path

### ISSUE THREAD

**Issue by dj-kefir-siorbacz** [pauzii/PhaseBetweener#6]
Data from Unity is exported here:
![image](https://github.com/pauzii/PhaseBetweener/assets/135321152/ba1c56d4-1b24-410d-b112-e4fc8ea987e9)

While the `InBetweeningNetwork.py` expects them in a different folder:
https://github.com/pauzii/PhaseBetweener/blob/b8f4e4df3456f6218ce2434d8d875f78a3799ad9/DeepLearningONNX/Models/GNN/InBetweeningNetwork.py#L15

**Comment by 0mil** [comment]
@dj-kefir-siorbacz 
How can you get the datasets like Input.txt, Output.txt, InputLabels.txt, I/ONorm.txt? I can't find them in the repository.

**Comment by dj-kefir-siorbacz** [comment]
@0mil  It's been a long time, I don't remember, unfortunately. But they are not by default in the repo - you need to generate them inside of Unity

**Comment by 0mil** [comment]
@dj-kefir-siorbacz Thank you for answering! I will try to generate it using Unity. :)
